# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5317a5c633171ef770cb0cee6042dd782a6b5d05d9bfca30d2f1a0bcc9b7ed0a609b00a80f739c138d638ef22b5688652bdcdb4513b480d6a6ada154f6d7ccb4

test:
  secret_key_base: ce94f955574ac424cc7c57966e0b7f9838d94d16314862d9f656394b6398353bd9c379d453766455b9209cfbf8d2da795e1f0d53b157bd2acf3716fd4ae154b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
